name: auto-create-milestone

on:
  #schedule:
   # - cron: 0 0 * * SAT
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: readmeio/scheduled-milestones@v1.0.0
        id: run
        with:
          token: ${{ secrets.MILESTONES }}
          title: d-
          days: Friday
          count: 4
          format: YYYY.MM.DD

      - name: result
        run: echo ${{ steps.run.outputs.milestones }}
