name: auto-create-milestone

on:
  #schedule:
   # - cron: 0 0 * * SAT
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  milestones:
    runs-on: ubuntu-latest
    name: Create Milestones automaticly
    steps:
    - name: Create Milestones
      uses: MrGossett/github-action-milestone-schedule@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MILESTONES }}
      with:
        recurrence: 'FREQ=WEEKLY;BYDAY=FR;DTSTART=20191213T220000Z'
        format: 'Done 06-Jan-02'
        count: 4
