
name: Pytest_report_testing

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [ master ]
permissions:
  contents: read
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install selenium
          pip install pytest-playwright
          pip install requests
          pip install loguru
      - name: execute py script 
        env:
          SOME_SECRET: ${{ secrets.TEST_SECRET }}
        run: pytest --junit-xml=test-results.xml
      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:

          path: test-results.xml

    # Add a summary of the results at the top of the report
    # Default: true
          summary: true

    # Select which results should be included in the report.
    # Follows the same syntax as
    # `pytest -r`
    # Default: fEX
          display-options: fEX

    # Fail the workflow if no JUnit XML was found.
    # Default: true
          fail-on-empty: true
