name: Headless_robot_tests

on:
  schedule:
    - cron: '* * * * *' 
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install webdrivermanager
        webdrivermanager chrome
    - name: Run robot tests
      #run: |
         # robot -d ./logs -v browser:chromium -v headless:true test_rozetka_main_page_search.robot
      #run:  robot test_rozetka_main_page_search.robot
      run: robot *.robot
