name: MarketplaceTest

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [ master ]
permissions:
  contents: read
  checks: write
  pull-requests: write
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
      - name: execute py script # run main.py
        env:
          SOME_SECRET: ${{ secrets.TEST_SECRET }}
        run: python test_capitalize.py
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - uses: ./
        name: json to file
        with:
          json: '{"foo": "test"}'
          filename: 'test.json'
        id: store-json

      - shell: pwsh        
        run: |
         $content = Get-Content -Path 'test.json'
         $test = $content | ConvertFrom-Json
         if ($test.foo -eq 'test') {
            Write-Host "File found correct"
         } 
         else {
            Write-Host "Found this json:"
            Write-Host $test | ConvertTo-Json
         }
            
      - name: Upload result file as artefact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v2.3.1
        with: 
          name: test
          path: test.json
            
